### ISSUE TITLE
Cesar Rodriguez Garden

### ISSUE THREAD

**Issue by cesarrodrig** [binyamin/dg-webring#1]
Hi, it's exciting to start a webring around digital gardens! My name is Cesar Rodriguez and my garden is [here](https://cesarrodrig.github.io/garden/). 

I have to look into implementing an RSS feed though. Any tips are appreciated. My garden is built using TiddlyWiki.

**Comment by binyamin** [comment]
Okay, you're in! Do you know what to do from here?

**Comment by cesarrodrig** [comment]
Awesome! I'll update my digital garden this week.
