### ISSUE TITLE
Digital Gardens Webring Addition

### ISSUE THREAD

**Issue by brisray** [binyamin/dg-webring#24]
Hello Binyamin,

are you still running the Digital Gardens webring? If so I would like to become a member of it. My site is Ray's Miscellany at https://brisray.com/ and I will be adding the webring code to the page at https://brisray.com/utils/webrings.htm with the others I am a member of.

If you are still the webring, you might want to look at the list at https://dg-webring.netlify.app/ as some of the sites have disappeared.

Ray

Ray Thomas
https://brisray.com/
https://hmsgambia.org/

**Comment by binyamin** [comment]
I'm not really interested in running it anymore. I haven't used a digital garden in a few years. I'm not really sure what to do. If you're interested, I can transfer it to you.

**Comment by brisray** [comment]
Let me talk to a couple of people. I’d hate to see these webrings disappear and I might know someone who may want to look after it. If not, perhaps I will.

 

Ray

**Comment by jackeyjack1** [comment]
Yo, I'll gladly take it.
- foreverliketh.is

**Comment by binyamin** [comment]
@jackeyjack1 Still interested?

**Comment by jackeyjack1** [comment]
@binyamin Heck yeah!

**Comment by binyamin** [comment]
see #30
