### ISSUE TITLE
add foreverlikethis

### ISSUE THREAD

**Issue by jackeyjack1** [binyamin/dg-webring#25]
Nice to e-meet you Binyamin,

I love webrings and my site is primarily a Digital Garden - would love to join!

https://foreverliketh.is/

**Comment by binyamin** [comment]
Continuing from https://github.com/binyamin/dg-webring/issues/24#issuecomment-1539032504

What is your netlify account info, so I can transfer the site to you?

**Comment by jackeyjack1** [comment]
@binyamin I've sent you an email, let me know if anything

**Comment by binyamin** [comment]
Yep, sorry, I just haven't gotten to it yet.

**Comment by jackeyjack1** [comment]
Understood, no problemo. 👍

**Comment by binyamin** [comment]
See #30
