### ISSUE TITLE
Eric Gregorich

### ISSUE THREAD

**Issue by ericgregorich** [binyamin/dg-webring#6]
Eric Gregorich
https://publish.obsidian.md/ericgregorich

**Comment by binyamin** [comment]
@ericgregorich It's nice to have you! How did you find out about the webring? By the way, I'm going to have to tweak the site a bit before obsidian urls work.

**Comment by ericgregorich** [comment]
I found it through Rosie Campbell's site. 

I think Obsidian is going to support custom domains by the end of the year. Maybe that will help?

**Comment by binyamin** [comment]
@ericgregorich I'm sorry that I never returned to this issue. :facepalm:. I noticed that, on your site, it says you're not publishing your vault currently. Do you want me to keep this issue open, or can I close it?

**Comment by ericgregorich** [comment]
You can close it. I'm not publishing at the moment. Thanks!

Eric Gregorich
https://ericgregorich.com/

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
